name: InvseeTowny
author: Moulberry
version: 1.1.0
main: com.zruybal.profile.Profile
depends: [Towny, mcMMO, PermissionsEx, Vault]
commands:
 profile:
  description:
   Allows players to see the inventory and towny stats of another.
  useage:
   /profile [player]
 setbio:
  description:
   Sets your autobiography, viewable through /profile
  useage:
   /setbio [bio]